gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/affine.out codes/latest_affine.cpp
gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/arith.out codes/im_arith.cpp
gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/dist.out codes/im_dist.cpp
gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/fourier.out codes/im_fourier.cpp
gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/hist.out codes/im_hist.cpp
gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/morpho.out codes/im_morphology.cpp
gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/neigh.out codes/im_nbrhood.cpp
gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/path.out codes/im_path.cpp
gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/point.out codes/im_point.cpp
gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/segment.out codes/im_segment.cpp
gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/colour.out codes/im_colour.cpp
gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/colour2.out codes/im_colourLin.cpp
gcc -I/usr/local/src/OpenCV-2.3.1/include/opencv/ -L/usr/local/src/OpenCV-2.3.1/build/lib/ -lcv -lhighgui -lstdc++ -o execs/colour3.out codes/im_colhist.cpp
